project:
  type: website
  output-dir: docs

website:
  title: "Yusuf Khalil -  CPLN 5920 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: labs/lab_0/lab_0.qmd
            text: "Lab 0: dplyr Basics"  
          - href: labs/lab_1/lab_1.qmd
            text: "Lab 1: Census Data Exploration"
          - href: labs/lab_2/lab_2.qmd
            text: "Lab 2: Geospatial Analysis"
          - href: labs/lab_3/Khalil_Yusuf_Appendix.qmd
            text: "Lab 3: Hedonic Housing Price Model"
            
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
