<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Yusuf Khalil">
<meta name="dcterms.date" content="2026-02-09">

<title>Lab 1: Census Data Quality for Policy Decisions – Yusuf Khalil - CPLN 5920 Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Yusuf Khalil - CPLN 5920 Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="../../labs/lab_0/lab_0.html">
 <span class="dropdown-text">Lab 0: dplyr Basics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../labs/lab_1/lab_1.html">
 <span class="dropdown-text">Lab 1: Census Data Exploration</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#assignment-overview" id="toc-assignment-overview" class="nav-link active" data-scroll-target="#assignment-overview">Assignment Overview</a>
  <ul class="collapse">
  <li><a href="#scenario" id="toc-scenario" class="nav-link" data-scroll-target="#scenario">Scenario</a></li>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#submission-instructions" id="toc-submission-instructions" class="nav-link" data-scroll-target="#submission-instructions">Submission Instructions</a></li>
  </ul></li>
  <li><a href="#part-1-portfolio-integration" id="toc-part-1-portfolio-integration" class="nav-link" data-scroll-target="#part-1-portfolio-integration">Part 1: Portfolio Integration</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-2-county-level-resource-assessment" id="toc-part-2-county-level-resource-assessment" class="nav-link" data-scroll-target="#part-2-county-level-resource-assessment">Part 2: County-Level Resource Assessment</a>
  <ul class="collapse">
  <li><a href="#data-retrieval" id="toc-data-retrieval" class="nav-link" data-scroll-target="#data-retrieval">2.1 Data Retrieval</a></li>
  <li><a href="#data-quality-assessment" id="toc-data-quality-assessment" class="nav-link" data-scroll-target="#data-quality-assessment">2.2 Data Quality Assessment</a></li>
  <li><a href="#high-uncertainty-counties" id="toc-high-uncertainty-counties" class="nav-link" data-scroll-target="#high-uncertainty-counties">2.3 High Uncertainty Counties</a></li>
  </ul></li>
  <li><a href="#part-3-neighborhood-level-analysis" id="toc-part-3-neighborhood-level-analysis" class="nav-link" data-scroll-target="#part-3-neighborhood-level-analysis">Part 3: Neighborhood-Level Analysis</a>
  <ul class="collapse">
  <li><a href="#focus-area-selection" id="toc-focus-area-selection" class="nav-link" data-scroll-target="#focus-area-selection">3.1 Focus Area Selection</a></li>
  <li><a href="#tract-level-demographics" id="toc-tract-level-demographics" class="nav-link" data-scroll-target="#tract-level-demographics">3.2 Tract-Level Demographics</a></li>
  <li><a href="#demographic-analysis" id="toc-demographic-analysis" class="nav-link" data-scroll-target="#demographic-analysis">3.3 Demographic Analysis</a></li>
  </ul></li>
  <li><a href="#part-4-comprehensive-data-quality-evaluation" id="toc-part-4-comprehensive-data-quality-evaluation" class="nav-link" data-scroll-target="#part-4-comprehensive-data-quality-evaluation">Part 4: Comprehensive Data Quality Evaluation</a>
  <ul class="collapse">
  <li><a href="#moe-analysis-for-demographic-variables" id="toc-moe-analysis-for-demographic-variables" class="nav-link" data-scroll-target="#moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</a></li>
  <li><a href="#pattern-analysis" id="toc-pattern-analysis" class="nav-link" data-scroll-target="#pattern-analysis">4.2 Pattern Analysis</a></li>
  </ul></li>
  <li><a href="#part-5-policy-recommendations" id="toc-part-5-policy-recommendations" class="nav-link" data-scroll-target="#part-5-policy-recommendations">Part 5: Policy Recommendations</a>
  <ul class="collapse">
  <li><a href="#analysis-integration-and-professional-summary" id="toc-analysis-integration-and-professional-summary" class="nav-link" data-scroll-target="#analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</a></li>
  <li><a href="#specific-recommendations" id="toc-specific-recommendations" class="nav-link" data-scroll-target="#specific-recommendations">6.3 Specific Recommendations</a></li>
  <li><a href="#questions-for-further-investigation" id="toc-questions-for-further-investigation" class="nav-link" data-scroll-target="#questions-for-further-investigation">Questions for Further Investigation</a></li>
  </ul></li>
  <li><a href="#technical-notes" id="toc-technical-notes" class="nav-link" data-scroll-target="#technical-notes">Technical Notes</a>
  <ul class="collapse">
  <li><a href="#submission-checklist" id="toc-submission-checklist" class="nav-link" data-scroll-target="#submission-checklist">Submission Checklist</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 1: Census Data Quality for Policy Decisions</h1>
<p class="subtitle lead">Evaluating Data Reliability for Algorithmic Decision-Making</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Yusuf Khalil </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="assignment-overview" class="level1">
<h1>Assignment Overview</h1>
<section id="scenario" class="level2">
<h2 class="anchored" data-anchor-id="scenario">Scenario</h2>
<p>You are a data analyst for the <strong>Pennsylvania Department of Human Services</strong>. The department is considering implementing an algorithmic system to identify communities that should receive priority for social service funding and outreach programs. Your supervisor has asked you to evaluate the quality and reliability of available census data to inform this decision.</p>
<p>Drawing on our Week 2 discussion of algorithmic bias, you need to assess not just what the data shows, but how reliable it is and what communities might be affected by data quality issues.</p>
</section>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<ul>
<li>Apply dplyr functions to real census data for policy analysis</li>
<li>Evaluate data quality using margins of error</li>
<li>Connect technical analysis to algorithmic decision-making</li>
<li>Identify potential equity implications of data reliability issues</li>
<li>Create professional documentation for policy stakeholders</li>
</ul>
</section>
<section id="submission-instructions" class="level2">
<h2 class="anchored" data-anchor-id="submission-instructions">Submission Instructions</h2>
<p><strong>Submit by posting your updated portfolio link on Canvas.</strong> Your assignment should be accessible at <code>your-portfolio-url/labs/lab_1/</code></p>
<p>Make sure to update your <code>_quarto.yml</code> navigation to include this assignment under an “Labs” menu.</p>
</section>
</section>
<section id="part-1-portfolio-integration" class="level1">
<h1>Part 1: Portfolio Integration</h1>
<p>Create this assignment in your portfolio repository under an <code>labs/lab_1/</code> folder structure. Update your navigation menu to include:</p>
<pre><code>- text: Assignments
  menu:
    - href: labs/lab_1/your_file_name.qmd
      text: "Lab 1: Census Data Exploration"</code></pre>
<p>If there is a special character like a colon, you need use double quote mark so that the quarto can identify this as text</p>
</section>
<section id="setup" class="level1">
<h1>Setup</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages (hint: you need tidycensus, tidyverse, and knitr)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your Census API key</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose your state for analysis - assign it to a variable called my_state</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>my_state <span class="ot">&lt;-</span> <span class="st">"Pa"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>State Selection:</strong> I have chosen <strong>Pennsylvania</strong> for this analysis because: I am comfortable with the states geography and its demography</p>
</section>
<section id="part-2-county-level-resource-assessment" class="level1">
<h1>Part 2: County-Level Resource Assessment</h1>
<section id="data-retrieval" class="level2">
<h2 class="anchored" data-anchor-id="data-retrieval">2.1 Data Retrieval</h2>
<p><strong>Your Task:</strong> Use <code>get_acs()</code> to retrieve county-level data for your chosen state.</p>
<p><strong>Requirements:</strong> - Geography: county level - Variables: median household income (B19013_001) and total population (B01003_001)<br>
- Year: 2022 - Survey: acs5 - Output format: wide</p>
<p><strong>Hint:</strong> Remember to give your variables descriptive names using the <code>variables = c(name = "code")</code> syntax.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your get_acs() code here</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>state_pop <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"state"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="st">"B01003_001"</span>,  <span class="co"># Total population</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2022</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(state_pop)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 52
Columns: 5
$ GEOID    &lt;chr&gt; "01", "02", "04", "05", "06", "08", "09", "10", "11", "12", "…
$ NAME     &lt;chr&gt; "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Co…
$ variable &lt;chr&gt; "B01003_001", "B01003_001", "B01003_001", "B01003_001", "B010…
$ estimate &lt;dbl&gt; 5028092, 734821, 7172282, 3018669, 39356104, 5770790, 3611317…
$ moe      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>pa_data <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"county"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">c</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_pop =</span> <span class="st">"B01003_001"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_income =</span> <span class="st">"B19013_001"</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> <span class="st">"PA"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2022</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span>  <span class="co"># Makes analysis easier</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pa_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  GEOID NAME                 total_popE total_popM median_incomeE median_incomeM
  &lt;chr&gt; &lt;chr&gt;                     &lt;dbl&gt;      &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;
1 42001 Adams County, Penns…     104604         NA          78975           3334
2 42003 Allegheny County, P…    1245310         NA          72537            869
3 42005 Armstrong County, P…      65538         NA          61011           2202
4 42007 Beaver County, Penn…     167629         NA          67194           1531
5 42009 Bedford County, Pen…      47613         NA          58337           2606
6 42011 Berks County, Penns…     428483         NA          74617           1191</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean the county names to remove state name and "County" </span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use mutate() with str_remove()</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>pa_clean <span class="ot">&lt;-</span> pa_data <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Remove state name from county names</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_name =</span> <span class="fu">str_remove</span>(NAME, <span class="st">", Pennsylvania"</span>),</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Remove "County" word</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_name =</span> <span class="fu">str_remove</span>(county_name, <span class="st">" County"</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="data-quality-assessment" class="level2">
<h2 class="anchored" data-anchor-id="data-quality-assessment">2.2 Data Quality Assessment</h2>
<p><strong>Your Task:</strong> Calculate margin of error percentages and create reliability categories.</p>
<p><strong>Requirements:</strong> - Calculate MOE percentage: (margin of error / estimate) * 100 - Create reliability categories: - High Confidence: MOE &lt; 5% - Moderate Confidence: MOE 5-10%<br>
- Low Confidence: MOE &gt; 10% - Create a flag for unreliable estimates (MOE &gt; 10%)</p>
<p><strong>Hint:</strong> Use <code>mutate()</code> with <code>case_when()</code> for the categories.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentage and reliability categories using mutate()</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(pa_clean, NAME, county_name)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 67 × 2
   NAME                           county_name
   &lt;chr&gt;                          &lt;chr&gt;      
 1 Adams County, Pennsylvania     Adams      
 2 Allegheny County, Pennsylvania Allegheny  
 3 Armstrong County, Pennsylvania Armstrong  
 4 Beaver County, Pennsylvania    Beaver     
 5 Bedford County, Pennsylvania   Bedford    
 6 Berks County, Pennsylvania     Berks      
 7 Blair County, Pennsylvania     Blair      
 8 Bradford County, Pennsylvania  Bradford   
 9 Bucks County, Pennsylvania     Bucks      
10 Butler County, Pennsylvania    Butler     
# ℹ 57 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>pa_reliability <span class="ot">&lt;-</span> pa_clean <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate MOE as percentage of estimate</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">moe_percentage =</span> <span class="fu">round</span>((median_incomeM <span class="sc">/</span> median_incomeE) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create reliability categories</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">reliability =</span> <span class="fu">case_when</span>(</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>      moe_percentage <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"High Confidence"</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>      moe_percentage <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> moe_percentage <span class="sc">&lt;=</span> <span class="dv">8</span> <span class="sc">~</span> <span class="st">"Moderate"</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>      moe_percentage <span class="sc">&gt;</span> <span class="dv">8</span> <span class="sc">~</span> <span class="st">"Low Confidence"</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(pa_reliability, reliability)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  reliability         n
  &lt;chr&gt;           &lt;int&gt;
1 High Confidence    57
2 Low Confidence      2
3 Moderate            8</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary showing count of counties in each reliability category</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use count() and mutate() to add percentages</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="high-uncertainty-counties" class="level2">
<h2 class="anchored" data-anchor-id="high-uncertainty-counties">2.3 High Uncertainty Counties</h2>
<p><strong>Your Task:</strong> Identify the 5 counties with the highest MOE percentages.</p>
<p><strong>Requirements:</strong> - Sort by MOE percentage (highest first) - Select the top 5 counties - Display: county name, median income, margin of error, MOE percentage, reliability category - Format as a professional table using <code>kable()</code></p>
<p><strong>Hint:</strong> Use <code>arrange()</code>, <code>slice()</code>, and <code>select()</code> functions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create table of top 5 counties by MOE percentage</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Find counties with highest uncertainty</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>high_uncertainty <span class="ot">&lt;-</span> pa_reliability <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(moe_percentage <span class="sc">&gt;</span> <span class="dv">8</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(moe_percentage)) <span class="sc">%&gt;%</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(county_name, median_incomeE, moe_percentage)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary by reliability category  </span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>reliability_summary <span class="ot">&lt;-</span> pa_reliability <span class="sc">%&gt;%</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(reliability) <span class="sc">%&gt;%</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">counties =</span> <span class="fu">n</span>(),</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_income =</span> <span class="fu">round</span>(<span class="fu">mean</span>(median_incomeE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">0</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as table with kable() - include appropriate column names and caption</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Create formatted table</span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(high_uncertainty,</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Median Income"</span>, <span class="st">"MOE %"</span>),</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Counties with Highest Income Data Uncertainty"</span>,</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Counties with Highest Income Data Uncertainty</caption>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">MOE %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Forest</td>
<td style="text-align: right;">46,188</td>
<td style="text-align: right;">9.99</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sullivan</td>
<td style="text-align: right;">62,910</td>
<td style="text-align: right;">9.25</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Data Quality Commentary:</strong></p>
<p>Forest and Sullivan counties, Pennsylvania’s smallest by population, show the highest income data uncertainty (MOE &gt; 9%), reflecting the well-documented relationship between small sample sizes and imprecise ACS estimates. Algorithms relying on these point estimates risk systematically misallocating resources to rural communities, where the true median income could plausibly differ by several thousand dollars.</p>
</section>
</section>
<section id="part-3-neighborhood-level-analysis" class="level1">
<h1>Part 3: Neighborhood-Level Analysis</h1>
<section id="focus-area-selection" class="level2">
<h2 class="anchored" data-anchor-id="focus-area-selection">3.1 Focus Area Selection</h2>
<p><strong>Your Task:</strong> Select 2-3 counties from your reliability analysis for detailed tract-level study.</p>
<p><strong>Strategy:</strong> Choose counties that represent different reliability levels (e.g., 1 high confidence, 1 moderate, 1 low confidence) to compare how data quality varies.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use filter() to select 2-3 counties from your county_reliability data</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Store the selected counties in a variable called selected_counties</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the selected counties with their key characteristics</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: county name, median income, MOE percentage, reliability category</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>focus_area <span class="ot">&lt;-</span> pa_reliability <span class="sc">%&gt;%</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(NAME <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Forest County, Pennsylvania"</span>, <span class="st">"Snyder County, Pennsylvania"</span>, <span class="st">"Montgomery County, Pennsylvania"</span>))</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#select(NAME == c("Forest County, Pennsylvania", "Snyder County, Pennsylvania", "Montgomery County, Pennsylvania"))</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>selected_counties <span class="ot">&lt;-</span> focus_area <span class="sc">%&gt;%</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(GEOID,NAME, median_incomeE, moe_percentage, reliability)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(selected_counties, </span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"GEOID"</span>, <span class="st">"County"</span>, <span class="st">"Median Income"</span>, <span class="st">"MOE %"</span>, <span class="st">"Reliability Category"</span>),</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Selected Counties"</span>,</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>      )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Selected Counties</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 40%">
<col style="width: 17%">
<col style="width: 7%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">GEOID</th>
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">MOE %</th>
<th style="text-align: left;">Reliability Category</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">42053</td>
<td style="text-align: left;">Forest County, Pennsylvania</td>
<td style="text-align: right;">46,188</td>
<td style="text-align: right;">9.99</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">42091</td>
<td style="text-align: left;">Montgomery County, Pennsylvania</td>
<td style="text-align: right;">107,441</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: left;">High Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">42109</td>
<td style="text-align: left;">Snyder County, Pennsylvania</td>
<td style="text-align: right;">65,914</td>
<td style="text-align: right;">5.56</td>
<td style="text-align: left;">Moderate</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Comment on the output:</strong> I selected three County’s each from a different reliability category.</p>
</section>
<section id="tract-level-demographics" class="level2">
<h2 class="anchored" data-anchor-id="tract-level-demographics">3.2 Tract-Level Demographics</h2>
<p><strong>Your Task:</strong> Get demographic data for census tracts in your selected counties.</p>
<p><strong>Requirements:</strong> - Geography: tract level - Variables: white alone (B03002_003), Black/African American (B03002_004), Hispanic/Latino (B03002_012), total population (B03002_001) - Use the same state and year as before - Output format: wide - <strong>Challenge:</strong> You’ll need county codes, not names. Look at the GEOID patterns in your county data for hints.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define your race/ethnicity variables with descriptive names</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>Selected_data <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"tract"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">c</span>(<span class="at">White_alone =</span> <span class="st">"B03002_003"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">Black_AA =</span> <span class="st">"B03002_004"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">Hisp_lat =</span> <span class="st">"B03002_012"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">Total_pop =</span> <span class="st">"B03002_001"</span>),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> <span class="st">"PA"</span>,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">county =</span> <span class="fu">c</span>(<span class="st">"053"</span>, <span class="st">"091"</span>, <span class="st">"109"</span>),</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2023</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span>,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Use get_acs() to retrieve tract-level data</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: You may need to specify county codes in the county parameter</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage of each group using mutate()</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Create percentages for white, Black, and Hispanic populations</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>Revised_data <span class="ot">&lt;-</span> Selected_data <span class="sc">%&gt;%</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">white_perc =</span> (White_aloneE<span class="sc">/</span>Total_popE)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>         <span class="at">black_perc =</span> (Black_AAE<span class="sc">/</span>Total_popE)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>         <span class="at">Hisp_perc =</span> (Hisp_latE<span class="sc">/</span>Total_popE)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>         </span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>         )</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Add readable tract and county name columns using str_extract() or similar</span></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>Final_Data <span class="ot">&lt;-</span> Revised_data <span class="sc">%&gt;%</span></span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">County =</span> <span class="fu">str_extract</span>(NAME, <span class="st">"Forest County|Montgomery County|Snyder County"</span>),</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>         <span class="at">Tract =</span> <span class="fu">str_extract</span>(NAME, <span class="st">"Census Tract [0-9.]+"</span>)</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>         )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="demographic-analysis" class="level2">
<h2 class="anchored" data-anchor-id="demographic-analysis">3.3 Demographic Analysis</h2>
<p><strong>Your Task:</strong> Analyze the demographic patterns in your selected areas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the tract with the highest percentage of Hispanic/Latino residents</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use arrange() and slice() to get the top tract</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>Demo_analysis <span class="ot">&lt;-</span> Final_Data <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Hisp_perc)) <span class="sc">%&gt;%</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">3</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average demographics by county using group_by() and summarize()</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: number of tracts, average percentage for each racial/ethnic group</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>avg_demo <span class="ot">&lt;-</span> Final_Data <span class="sc">%&gt;%</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(white_perc)) <span class="sc">%&gt;%</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(County) <span class="sc">%&gt;%</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_white =</span> <span class="fu">round</span>(<span class="fu">mean</span>(white_perc), <span class="dv">3</span>),</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_black =</span> <span class="fu">round</span>(<span class="fu">mean</span>(black_perc),<span class="dv">3</span>),</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_hisp =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Hisp_perc),<span class="dv">3</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a nicely formatted table of your results using kable()</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(avg_demo,</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County Names"</span>, <span class="st">"Number of Census Tracts"</span>, <span class="st">"Average White %"</span>, <span class="st">"Average Black %"</span>, <span class="st">"Average Hispanic %"</span>),</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Average Demographic"</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>      )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Average Demographic</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 25%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County Names</th>
<th style="text-align: right;">Number of Census Tracts</th>
<th style="text-align: right;">Average White %</th>
<th style="text-align: right;">Average Black %</th>
<th style="text-align: right;">Average Hispanic %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Forest County</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">81.679</td>
<td style="text-align: right;">11.203</td>
<td style="text-align: right;">4.262</td>
</tr>
<tr class="even">
<td style="text-align: left;">Montgomery County</td>
<td style="text-align: right;">216</td>
<td style="text-align: right;">72.487</td>
<td style="text-align: right;">9.349</td>
<td style="text-align: right;">6.566</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Snyder County</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">93.154</td>
<td style="text-align: right;">1.309</td>
<td style="text-align: right;">2.657</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="part-4-comprehensive-data-quality-evaluation" class="level1">
<h1>Part 4: Comprehensive Data Quality Evaluation</h1>
<section id="moe-analysis-for-demographic-variables" class="level2">
<h2 class="anchored" data-anchor-id="moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</h2>
<p><strong>Your Task:</strong> Examine margins of error for demographic variables to see if some communities have less reliable data.</p>
<p><strong>Requirements:</strong> - Calculate MOE percentages for each demographic variable - Flag tracts where any demographic variable has MOE &gt; 15% - Create summary statistics</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentages for white, Black, and Hispanic variables</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use the same formula as before (margin/estimate * 100)</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>Final_Moe <span class="ot">&lt;-</span> Final_Data <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">white_moe =</span> <span class="fu">round</span>((White_aloneM<span class="sc">/</span>White_aloneE)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>),</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">black_moe =</span> <span class="fu">round</span>((Black_AAM<span class="sc">/</span>Black_AAE)<span class="sc">*</span><span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">hisp_moe =</span> <span class="fu">round</span>((Hisp_latM<span class="sc">/</span>Hisp_latE)<span class="sc">*</span><span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">pop_moe =</span> <span class="fu">round</span>((Total_popM<span class="sc">/</span>Total_popE)<span class="sc">*</span><span class="dv">100</span>, <span class="dv">2</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(Final_Moe<span class="sc">$</span>white_moe)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   0%   25%   50%   75%  100% 
 1.91 11.46 14.13 17.95   Inf </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a flag for tracts with high MOE on any demographic variable</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Use logical operators (| for OR) in an ifelse() statement</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>Flagged_data <span class="ot">&lt;-</span> Final_Moe <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">c</span>(white_moe, black_moe, hisp_moe),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>           <span class="sc">~</span><span class="fu">if_else</span>(. <span class="sc">&gt;</span> <span class="dv">15</span>, <span class="st">"Flagged"</span>, <span class="st">"Non-Flagged"</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>           </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>           )</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>   <span class="co"># flagged = case_when(white_moe &gt;= 15 ~ "Flagged",</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    <span class="co">#                    white_moe &lt;= 15 ~ "Not-flagged",</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>     <span class="co">#                   black_moe &gt;= 15 ~ "Flagged",</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>      <span class="co">#                  black_moe &lt;= 15 ~ "Not-flagged",</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>       <span class="co">#                 hisp_moe &gt;= 15 ~ "Flagged",</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>        <span class="co">#                hisp_moe &lt;= 15 ~ "Not-flagged",)</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Create summary statistics showing how many tracts have data quality issues</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> Flagged_data <span class="sc">%&gt;%</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(County, white_moe) <span class="sc">%&gt;%</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(summary_stats,</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Reliability Issues"</span>, <span class="st">"Number of Tracts"</span>),</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Number of Census Tracts with Data Reliability Issues per County"</span></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>      )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Number of Census Tracts with Data Reliability Issues per County</caption>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: left;">Reliability Issues</th>
<th style="text-align: right;">Number of Tracts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Forest County</td>
<td style="text-align: left;">Non-Flagged</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Montgomery County</td>
<td style="text-align: left;">Flagged</td>
<td style="text-align: right;">101</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Montgomery County</td>
<td style="text-align: left;">Non-Flagged</td>
<td style="text-align: right;">118</td>
</tr>
<tr class="even">
<td style="text-align: left;">Snyder County</td>
<td style="text-align: left;">Non-Flagged</td>
<td style="text-align: right;">8</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="pattern-analysis" class="level2">
<h2 class="anchored" data-anchor-id="pattern-analysis">4.2 Pattern Analysis</h2>
<p><strong>Your Task:</strong> Investigate whether data quality problems are randomly distributed or concentrated in certain types of communities.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group tracts by whether they have high MOE issues</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average characteristics for each group:</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># - population size, demographic percentages</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>pattern_analysis <span class="ot">&lt;-</span> Flagged_data <span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(white_moe, black_moe, hisp_moe),</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"group"</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"MOE_flag"</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average characteristics for each group:</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="co"># - population size, demographic percentages</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group, MOE_flag) <span class="sc">%&gt;%</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_total_pop =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Total_popE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">0</span>),</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_white =</span> <span class="fu">round</span>(<span class="fu">mean</span>(white_perc, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>),</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_black =</span> <span class="fu">round</span>(<span class="fu">mean</span>(black_perc, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>),</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_hisp =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Hisp_perc, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>),</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Use group_by() and summarize() to create this comparison</span></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a professional table showing the patterns</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(pattern_analysis,</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Group"</span>, <span class="st">"MOE Flag"</span>, <span class="st">"Tracts"</span>, <span class="st">"Avg Pop"</span>,</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Avg White %"</span>, <span class="st">"Avg Black %"</span>, <span class="st">"Avg Hispanic %"</span>),</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Tract Characteristics by Demographic Data Reliability"</span>,</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>      <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tract Characteristics by Demographic Data Reliability</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: left;">MOE Flag</th>
<th style="text-align: right;">Tracts</th>
<th style="text-align: right;">Avg Pop</th>
<th style="text-align: right;">Avg White %</th>
<th style="text-align: right;">Avg Black %</th>
<th style="text-align: right;">Avg Hispanic %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">black_moe</td>
<td style="text-align: left;">Flagged</td>
<td style="text-align: right;">227</td>
<td style="text-align: right;">3,966</td>
<td style="text-align: right;">73.5</td>
<td style="text-align: right;">8.8</td>
<td style="text-align: right;">6.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">black_moe</td>
<td style="text-align: left;">Non-Flagged</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3,703</td>
<td style="text-align: right;">46.0</td>
<td style="text-align: right;">40.5</td>
<td style="text-align: right;">11.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hisp_moe</td>
<td style="text-align: left;">Flagged</td>
<td style="text-align: right;">229</td>
<td style="text-align: right;">3,964</td>
<td style="text-align: right;">73.3</td>
<td style="text-align: right;">9.1</td>
<td style="text-align: right;">6.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">white_moe</td>
<td style="text-align: left;">Flagged</td>
<td style="text-align: right;">101</td>
<td style="text-align: right;">3,327</td>
<td style="text-align: right;">64.6</td>
<td style="text-align: right;">14.2</td>
<td style="text-align: right;">8.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">white_moe</td>
<td style="text-align: left;">Non-Flagged</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">4,466</td>
<td style="text-align: right;">80.0</td>
<td style="text-align: right;">5.1</td>
<td style="text-align: right;">4.6</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Pattern Analysis:</strong> Data quality issues are not randomly distributed but concentrate in smaller, more diverse tracts. All 229 tracts were flagged for unreliable Hispanic data, and only 2 had reliable Black population estimates, both with unusually large Black populations (40.5%). Meanwhile, tracts with reliable white population data tend to be larger and more homogeneous. This reflects a fundamental sample size problem: when a group is a small share of a small population, the ACS cannot produce precise estimates, meaning the communities most relevant to equity-focused policy are those with the least reliable data.</p>
</section>
</section>
<section id="part-5-policy-recommendations" class="level1">
<h1>Part 5: Policy Recommendations</h1>
<section id="analysis-integration-and-professional-summary" class="level2">
<h2 class="anchored" data-anchor-id="analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</h2>
<p><strong>Your Task:</strong> Write an executive summary that integrates findings from all four analyses.</p>
<p><strong>Executive Summary Requirements:</strong> 1. <strong>Overall Pattern Identification</strong>: What are the systematic patterns across all your analyses? 2. <strong>Equity Assessment</strong>: Which communities face the greatest risk of algorithmic bias based on your findings? 3. <strong>Root Cause Analysis</strong>: What underlying factors drive both data quality issues and bias risk? 4. <strong>Strategic Recommendations</strong>: What should the Department implement to address these systematic issues?</p>
<p><strong>Executive Summary:</strong> The analysis reveals an inverse relationship between data reliability and the size of the Pennsylvania County. At the county level in Pennsylvania there were 2 counties with low confidence, 8 counties with moderate confidence but over 57 with high confidence. Those with lower confidence were typically smaller and more rural in nature. On the census tract level, we found that Hispanic and Black populations would have far less reliable data. For instance the number of white MOE that was flagged looking at all 3 counties was 128/229 census tracts with a MOE over 15%. In comparison, all 229 census tracts had Hispanic population recorded with a MOE of over 15%. Thus there is a clear disparity in terms of data reliability.</p>
<p>The communities facing the worst algorithmic bias are the Black and Hispanic population. Pattern analysis shows that tracts that were not flagged had a majority white population. For instance, in our study, tracts that were not flagged had a Black population of 5.1% and Hispanic population of 4.6%. This means an equity focused algorithm would be relying on the least precise data if it wanted to target minority population.</p>
<p>Since the ACS is a sample survey, for smaller populations it will garner fewer observations with wider MOE. This trend compounds spatially, with less populated tracts and counties having the largest MOE.</p>
<p>To address these systematic issues we recommend that the department adopts a tiered approach to using data for policy purposes. For survey data with a MOE &lt; 5%, this should be used for data analysis purposes. On the other hand, data with a MOE between 5% and 15% should be manually parsed through. Here any anomalies can be addressed and analysed. Data may still be used in these cases. Finally data with a MOE of over 15% should not be used. Instead, policymakers should rely on admiinistrative data on a local scale. Additionally, they may pursue community engagement activities to address these data inequalities.</p>
</section>
<section id="specific-recommendations" class="level2">
<h2 class="anchored" data-anchor-id="specific-recommendations">6.3 Specific Recommendations</h2>
<p><strong>Your Task:</strong> Create a decision framework for algorithm implementation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary table using your county reliability data</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Include: county name, median income, MOE percentage, reliability category</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>recommendations <span class="ot">&lt;-</span> pa_reliability <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(county_name, median_incomeE, moe_percentage, reliability) <span class="sc">%&gt;%</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a new column with algorithm recommendations using case_when():</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co"># - High Confidence: "Safe for algorithmic decisions"</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co"># - Moderate Confidence: "Use with caution - monitor outcomes"  </span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="co"># - Low Confidence: "Requires manual review or additional data"</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">algorithm_rec =</span> <span class="fu">case_when</span>(</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>      reliability <span class="sc">==</span> <span class="st">"High Confidence"</span> <span class="sc">~</span> <span class="st">"Safe for algorithmic decisions"</span>,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>      reliability <span class="sc">==</span> <span class="st">"Moderate"</span> <span class="sc">~</span> <span class="st">"Use with caution - monitor outcomes"</span>,</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>      reliability <span class="sc">==</span> <span class="st">"Low Confidence"</span> <span class="sc">~</span> <span class="st">"Requires manual review or additional data"</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(moe_percentage))</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as a professional table with kable()</span></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(recommendations,</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Median Income"</span>, <span class="st">"MOE %"</span>, </span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Reliability"</span>, <span class="st">"Algorithm Recommendation"</span>),</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Decision Framework for Algorithm Implementation by County"</span>,</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Decision Framework for Algorithm Implementation by County</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 17%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">MOE %</th>
<th style="text-align: left;">Reliability</th>
<th style="text-align: left;">Algorithm Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Forest</td>
<td style="text-align: right;">46,188</td>
<td style="text-align: right;">9.99</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sullivan</td>
<td style="text-align: right;">62,910</td>
<td style="text-align: right;">9.25</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Union</td>
<td style="text-align: right;">64,914</td>
<td style="text-align: right;">7.32</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Montour</td>
<td style="text-align: right;">72,626</td>
<td style="text-align: right;">7.09</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Elk</td>
<td style="text-align: right;">61,672</td>
<td style="text-align: right;">6.63</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Greene</td>
<td style="text-align: right;">66,283</td>
<td style="text-align: right;">6.41</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cameron</td>
<td style="text-align: right;">46,186</td>
<td style="text-align: right;">5.64</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Snyder</td>
<td style="text-align: right;">65,914</td>
<td style="text-align: right;">5.56</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Carbon</td>
<td style="text-align: right;">64,538</td>
<td style="text-align: right;">5.31</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Warren</td>
<td style="text-align: right;">57,925</td>
<td style="text-align: right;">5.19</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pike</td>
<td style="text-align: right;">76,416</td>
<td style="text-align: right;">4.90</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Juniata</td>
<td style="text-align: right;">61,915</td>
<td style="text-align: right;">4.79</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wayne</td>
<td style="text-align: right;">59,240</td>
<td style="text-align: right;">4.79</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">McKean</td>
<td style="text-align: right;">57,861</td>
<td style="text-align: right;">4.75</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Huntingdon</td>
<td style="text-align: right;">61,300</td>
<td style="text-align: right;">4.72</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Indiana</td>
<td style="text-align: right;">57,170</td>
<td style="text-align: right;">4.65</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bedford</td>
<td style="text-align: right;">58,337</td>
<td style="text-align: right;">4.47</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Potter</td>
<td style="text-align: right;">56,491</td>
<td style="text-align: right;">4.42</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lycoming</td>
<td style="text-align: right;">63,437</td>
<td style="text-align: right;">4.39</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Clarion</td>
<td style="text-align: right;">58,690</td>
<td style="text-align: right;">4.37</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adams</td>
<td style="text-align: right;">78,975</td>
<td style="text-align: right;">4.22</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fayette</td>
<td style="text-align: right;">55,579</td>
<td style="text-align: right;">4.16</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Crawford</td>
<td style="text-align: right;">58,734</td>
<td style="text-align: right;">3.91</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Clinton</td>
<td style="text-align: right;">59,011</td>
<td style="text-align: right;">3.86</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wyoming</td>
<td style="text-align: right;">67,968</td>
<td style="text-align: right;">3.85</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Columbia</td>
<td style="text-align: right;">59,457</td>
<td style="text-align: right;">3.76</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fulton</td>
<td style="text-align: right;">63,153</td>
<td style="text-align: right;">3.65</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mercer</td>
<td style="text-align: right;">57,353</td>
<td style="text-align: right;">3.63</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Armstrong</td>
<td style="text-align: right;">61,011</td>
<td style="text-align: right;">3.61</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bradford</td>
<td style="text-align: right;">60,650</td>
<td style="text-align: right;">3.57</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Blair</td>
<td style="text-align: right;">59,386</td>
<td style="text-align: right;">3.47</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Venango</td>
<td style="text-align: right;">59,278</td>
<td style="text-align: right;">3.45</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mifflin</td>
<td style="text-align: right;">58,012</td>
<td style="text-align: right;">3.43</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jefferson</td>
<td style="text-align: right;">56,607</td>
<td style="text-align: right;">3.41</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cambria</td>
<td style="text-align: right;">54,221</td>
<td style="text-align: right;">3.34</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tioga</td>
<td style="text-align: right;">59,707</td>
<td style="text-align: right;">3.23</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Monroe</td>
<td style="text-align: right;">80,656</td>
<td style="text-align: right;">3.17</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Perry</td>
<td style="text-align: right;">76,103</td>
<td style="text-align: right;">3.17</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Susquehanna</td>
<td style="text-align: right;">63,968</td>
<td style="text-align: right;">3.14</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lawrence</td>
<td style="text-align: right;">57,585</td>
<td style="text-align: right;">3.07</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Franklin</td>
<td style="text-align: right;">71,808</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Clearfield</td>
<td style="text-align: right;">56,982</td>
<td style="text-align: right;">2.79</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Somerset</td>
<td style="text-align: right;">57,357</td>
<td style="text-align: right;">2.78</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Centre</td>
<td style="text-align: right;">70,087</td>
<td style="text-align: right;">2.77</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lebanon</td>
<td style="text-align: right;">72,532</td>
<td style="text-align: right;">2.69</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Northumberland</td>
<td style="text-align: right;">55,952</td>
<td style="text-align: right;">2.67</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Butler</td>
<td style="text-align: right;">82,932</td>
<td style="text-align: right;">2.61</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lackawanna</td>
<td style="text-align: right;">63,739</td>
<td style="text-align: right;">2.58</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Erie</td>
<td style="text-align: right;">59,396</td>
<td style="text-align: right;">2.55</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Schuylkill</td>
<td style="text-align: right;">63,574</td>
<td style="text-align: right;">2.40</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Washington</td>
<td style="text-align: right;">74,403</td>
<td style="text-align: right;">2.38</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Luzerne</td>
<td style="text-align: right;">60,836</td>
<td style="text-align: right;">2.35</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Beaver</td>
<td style="text-align: right;">67,194</td>
<td style="text-align: right;">2.28</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dauphin</td>
<td style="text-align: right;">71,046</td>
<td style="text-align: right;">2.27</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cumberland</td>
<td style="text-align: right;">82,849</td>
<td style="text-align: right;">2.20</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lehigh</td>
<td style="text-align: right;">74,973</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Westmoreland</td>
<td style="text-align: right;">69,454</td>
<td style="text-align: right;">1.99</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Northampton</td>
<td style="text-align: right;">82,201</td>
<td style="text-align: right;">1.93</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lancaster</td>
<td style="text-align: right;">81,458</td>
<td style="text-align: right;">1.79</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">York</td>
<td style="text-align: right;">79,183</td>
<td style="text-align: right;">1.79</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chester</td>
<td style="text-align: right;">118,574</td>
<td style="text-align: right;">1.70</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Berks</td>
<td style="text-align: right;">74,617</td>
<td style="text-align: right;">1.60</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delaware</td>
<td style="text-align: right;">86,390</td>
<td style="text-align: right;">1.53</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bucks</td>
<td style="text-align: right;">107,826</td>
<td style="text-align: right;">1.41</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Philadelphia</td>
<td style="text-align: right;">57,537</td>
<td style="text-align: right;">1.38</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Montgomery</td>
<td style="text-align: right;">107,441</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Allegheny</td>
<td style="text-align: right;">72,537</td>
<td style="text-align: right;">1.20</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>recommendations <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(reliability <span class="sc">==</span> <span class="st">"Low Confidence"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(county_name)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Forest"   "Sullivan"</code></pre>
</div>
</div>
<p><strong>Key Recommendations:</strong></p>
<p><strong>Your Task:</strong> Use your analysis results to provide specific guidance to the department.</p>
<ol type="1">
<li><p><strong>Counties suitable for immediate algorithmic implementation:</strong> Counties suitable for immediate algorithmic implementation: 57 of Pennsylvania’s 67 counties fall into the High Confidence category (MOE &lt; 5%), ranging from Allegheny (1.20%) to Pike (4.90%). These include the state’s most populous counties, Allegheny, Montgomery, Philadelphia, Bucks, Delaware, Chester, and Lancaster, as well as mid-size and smaller counties like Tioga, Fulton, and Potter. Their income estimates are precise enough that algorithmic resource allocation decisions can rely on this data without significant risk of misclassifying community need. The full list is: Pike, Juniata, Wayne, McKean, Huntingdon, Indiana, Bedford, Potter, Lycoming, Clarion, Adams, Fayette, Crawford, Clinton, Wyoming, Columbia, Fulton, Mercer, Armstrong, Bradford, Blair, Venango, Mifflin, Jefferson, Cambria, Tioga, Monroe, Perry, Susquehanna, Lawrence, Franklin, Clearfield, Somerset, Centre, Lebanon, Northumberland, Butler, Lackawanna, Erie, Schuylkill, Washington, Luzerne, Beaver, Dauphin, Cumberland, Lehigh, Westmoreland, Northampton, Lancaster, York, Chester, Berks, Delaware, Bucks, Philadelphia, Montgomery, and Allegheny.</p></li>
<li><p><strong>Counties requiring additional oversight:</strong> Counties requiring additional oversight: Eight counties fall into the Moderate Confidence category (MOE 5–8%): Union (7.32%), Montour (7.09%), Elk (6.63%), Greene (6.41%), Cameron (5.64%), Snyder (5.56%), Carbon (5.31%), and Warren (5.19%). Algorithmic outputs for these counties should be treated as guidance rather than definitive classifications. Any county whose MOE trends upward toward the 8% threshold in future ACS releases should be escalated for manual verification before funding decisions are made.</p></li>
<li><p><strong>Counties needing alternative approaches:</strong> Counties needing alternative approaches: Forest (9.99% MOE) and Sullivan (9.25% MOE) are the only two Low Confidence counties. Their small populations produce ACS estimates too imprecise for reliable automated targeting. For these counties, the Department should rely on local administrative records</p></li>
</ol>
</section>
<section id="questions-for-further-investigation" class="level2">
<h2 class="anchored" data-anchor-id="questions-for-further-investigation">Questions for Further Investigation</h2>
<p>How does population density correlate with data reliability? Our analysis suggests rural, sparsely populated counties like Forest and Sullivan have the highest MOE values, but a more systematic examination of population density at the tract level could reveal whether there is a clear threshold below which ACS estimates become unreliable for policy use.</p>
<p>Do home values follow the same reliability patterns as median income? If the Department were to incorporate housing market data such as median home value (ACS table B25077) into its algorithm, it would be important to assess whether the same counties and tracts flagged for income unreliability also have imprecise home value estimates, or whether property data offers a more stable alternative input.</p>
</section>
</section>
<section id="technical-notes" class="level1">
<h1>Technical Notes</h1>
<p><strong>Data Sources:</strong> - U.S. Census Bureau, American Community Survey 2018-2022 5-Year Estimates - Retrieved via tidycensus R package on 05/02/2026</p>
<p><strong>Reproducibility:</strong> - All analysis conducted in R version 2026 - Census API key required for replication 6986ece47521ee5f440e05d889a10797329fb58a - Complete code and documentation available at: https://muhammadyusufkhalil02-crypto.github.io/CPLN5920_yusufkhalil/</p>
<p><strong>Methodology Notes:</strong> Counties were selected to span all three reliability categories: Forest (Low Confidence), Snyder (Moderate), and Montgomery (High Confidence). Reliability thresholds were set at 5% and 8% MOE rather than the suggested 5% and 10% to better fit Pennsylvania’s distribution. The tract-level pull uses 2023 ACS data whilst the county-level pull uses 2022, which may introduce minor inconsistencies.</p>
<p><strong>Limitations:</strong> This analysis examines only 3 of Pennsylvania’s 67 counties at the tract level, limiting generalisability. Forest County has only 2 census tracts, making tract-level patterns from that county unreliable. The 15% MOE flagging threshold is somewhat arbitrary and could yield different results if adjusted. Finally, the ACS margins of error assume simple random sampling, whilst the actual survey design is more complex, meaning true uncertainty may differ from reported values.</p>
<hr>
<section id="submission-checklist" class="level2">
<h2 class="anchored" data-anchor-id="submission-checklist">Submission Checklist</h2>
<p>Before submitting your portfolio link on Canvas:</p>
<ul class="task-list">
<li><label><input type="checkbox" checked="">All code chunks run without errors</label></li>
<li><label><input type="checkbox" checked="">All “[Fill this in]” prompts have been completed</label></li>
<li><label><input type="checkbox" checked="">Tables are properly formatted and readable</label></li>
<li><label><input type="checkbox" checked="">Executive summary addresses all four required components</label></li>
<li><label><input type="checkbox" checked="">Portfolio navigation includes this assignment</label></li>
<li><label><input type="checkbox" checked="">Census API key is properly set</label></li>
<li><label><input type="checkbox" checked="">Document renders correctly to HTML</label></li>
</ul>
<p><strong>Remember:</strong> Submit your portfolio URL on Canvas, not the file itself. Your assignment should be accessible at <code>your-portfolio-url/labs/lab_1/your_file_name.html</code></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>